preload = /home/alpha/Pictures/Wallpapers/Beer-Girl.png
wallpaper = HDMI-A-1,  /home/alpha/Pictures/Wallpapers/Beer-Girl.png
wallpaper = eDP-1,     /home/alpha/Pictures/Wallpapers/Beer-Girl.png
splash = false
