exec-once = ssh-add /home/alpha/.ssh/id_ed25519_main
exec-once = hyprpaper
exec-once = systemctl --user start hypridle
exec-once = waybar -c /home/alpha/.config/waybar/config.jsonc -s /home/alpha/.config/waybar/style.css
exec-once = dunst
exec-once = gammastep -O 3000



