exec-once = ssh-add /home/alpha/.ssh/id_ed25519
exec-once = swww-daemon
exec-once = wal -R -n
exec-once = [workspace 9 silent] spotify
exec-once = [workspace 10 silent] sleep 3 && env ELECTRON_OZONE_PLATFORM_HINT=auto appimage-run /home/alpha/AppImages/ticktick/*
exec-once = systemctl --user start hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gammastep -O 3000
exec-once = sleep 1 && quickshell -p /home/alpha/.config/quickshell
#exec-once = sleep 1 && QML2_IMPORT_PATH=/run/current-system/sw/lib/qt-6/qml quickshell -p /home/alpha/.config/quickshell
