$mod = SUPER

# Applications
bind = $mod, Return, exec, kitty
bind = $mod, D, exec, qs ipc call launcher toggle
bind = $mod, A,	exec, qs ipc call dashboard toggle
bind = $mod, M, exec, qs ipc call music toggle
bind = $mod, W, exec, qs ipc call wallpaper toggle
bind = $mod, N, exec, qs ipc call notifcenter toggle
bind = $mod, C, exec, qs ipc call clipboard toggle
bind = $mod SHIFT, W, exec, ~/.config/scripts/random-wallpaper.sh
bind = $mod, X, exec, hyprlock
bind = $mod, Q, killactive

# Window state
bind = $mod, F, fullscreen, 0
bind = $mod, T, togglefloating

# Focus movement
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u

# Move windows
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, J, movewindow, d
bind = $mod SHIFT, K, movewindow, u

# Resize windows
binde = $mod CTRL, H, resizeactive, -50 0
binde = $mod CTRL, L, resizeactive,  50 0
binde = $mod CTRL, J, resizeactive,  0  50
binde = $mod CTRL, K, resizeactive,  0 -50

# Workspaces 1-9
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# Move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Audio
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind  = , XF86AudioMute,        exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Screenshot
bind = $mod, S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots_2026/screenshot-$(date +%Y%m%d-%H%M%S).png

# ScreenRecording
bind = $mod, R, exec, ~/.config/scripts/record-external.sh
bind = $mod ALT, R, exec, ~/.config/scripts/record-laptop.sh
bind = $mod CTRL, R, exec, ~/.config/scripts/record-region.sh

# Quit Hyprland
bind = $mod SHIFT, E, exit

# Mouse binds for window moving/resizing
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
